use serde::{Deserialize, Serialize};
use serde_json::Value;

use super::supervisor::SupervisorControlEvent;

#[derive(Clone, Debug, Deserialize, Serialize)]
pub struct Receipt {
    pub run_id: String,
    pub status: String,
    pub mode: String,
    pub summary: String,
    pub changed_files: Vec<String>,
    pub report: String,
    pub patch: String,
    pub worktree_patch: String,
    pub session: String,
    pub interventions: String,
    pub metrics: String,
    pub logs: String,
}

#[derive(Debug, Deserialize, Serialize)]
pub struct RunMetrics {
    pub start_timestamp: String,
    pub end_timestamp: String,
    pub wall_clock_ms: u128,
    pub worker_backend: String,
    pub opencode_command: Vec<String>,
    pub opencode_segments: Vec<Value>,
    pub opencode_exit_status: Option<i32>,
    pub opencode_provider: Option<String>,
    pub opencode_model: Option<String>,
    pub opencode_model_arg: Option<String>,
    pub opencode_session_label: Option<String>,
    pub opencode_session_id: Option<String>,
    pub opencode_resume_session_id: Option<String>,
    pub worker_session_reused: bool,
    pub interrupted_by_supervisor: bool,
    pub supervisor_control_action: Option<String>,
    pub supervisor_control_events: Vec<SupervisorControlEvent>,
    pub opencode_timed_out: bool,
    pub opencode_idle_timed_out: bool,
    pub heartbeat_count: u64,
    pub expect_patch: bool,
    pub intervention_count: usize,
    pub intervention_kinds: Vec<String>,
    pub intervention_artifact: String,
    pub empty_patch_followup_triggered: bool,
    pub empty_patch_followup_performed: bool,
    pub empty_patch_followup_patch_created: bool,
    pub empty_patch_followup_reason: Option<String>,
    pub empty_patch_followup_run_dir: Option<String>,
    pub revision_delta_expected: bool,
    pub revision_delta_bytes: u64,
    pub revision_noop_followup_triggered: bool,
    pub revision_noop_followup_performed: bool,
    pub revision_noop_followup_patch_created: bool,
    pub revision_noop_followup_reason: Option<String>,
    pub revision_noop_followup_run_dir: Option<String>,
    pub worker_self_review_enabled: bool,
    pub worker_self_review_triggered: bool,
    pub worker_self_review_performed: bool,
    pub worker_self_review_patch_changed: bool,
    pub worker_self_review_forced: bool,
    pub worker_self_review_reason: Option<String>,
    pub worker_self_review_run_dir: Option<String>,
    pub require_local: bool,
    pub local_inference_verified: bool,
    pub gpu_activity_observed: bool,
    pub backend_activity_observed: bool,
    pub verification_notes: Vec<String>,
    pub stdout_bytes: u64,
    pub stderr_bytes: u64,
    pub context_overflow_count: u64,
    pub context_overflow_last_message: Option<String>,
    pub worker_session_token_peak: Option<u64>,
    pub reasoning_trace_bytes: u64,
    pub reasoning_trace_event_count: u64,
    pub opencode_events_bytes: u64,
    pub opencode_event_count: u64,
    pub tool_events_bytes: u64,
    pub tool_event_count: u64,
    pub report_bytes: u64,
    pub patch_bytes: u64,
    pub worktree_patch_bytes: u64,
    pub session_bytes: u64,
    pub changed_file_count: usize,
    pub changed_line_count: usize,
    pub codex_token_usage: Option<u64>,
    pub approximate_codex_input_bytes: Option<u64>,
    pub approximate_codex_output_bytes: Option<u64>,
    pub artifact_files_read_by_codex: Vec<String>,
    pub notes: Vec<String>,
}
