use std::collections::BTreeSet;

use serde::{Deserialize, Serialize};

use crate::{
    DEFAULT_OPENCODE_LOCAL_MODEL, DEFAULT_OPENCODE_MODEL, DEFAULT_OPENCODE_PROVIDER, OpenCodeConfig,
};

/// Historical pitfalls for one worker model.
#[derive(Clone, Debug, Default, Deserialize, Eq, PartialEq, Serialize)]
#[serde(default)]
pub struct WorkerModelProfile {
    /// Canonical worker model label.
    pub model: String,
    /// Additional model/provider labels that should select this profile.
    pub aliases: Vec<String>,
    /// Expected changed-line target for one worker turn.
    pub target_patch_lines: Option<u64>,
    /// Expected changed-line ceiling for one worker turn.
    pub max_patch_lines: Option<u64>,
    /// Supervisor-only guidance for adapting worker instructions.
    pub supervisor_guidance: Vec<String>,
}

impl WorkerModelProfile {
    pub(crate) fn matches_opencode_worker(&self, config: &OpenCodeConfig) -> bool {
        let profile_names = self
            .identifiers()
            .into_iter()
            .map(normalize_model_identifier)
            .collect::<BTreeSet<_>>();
        config
            .selected_model_identifiers()
            .into_iter()
            .map(|identifier| normalize_model_identifier(&identifier))
            .any(|identifier| profile_names.contains(&identifier))
    }

    fn identifiers(&self) -> Vec<&str> {
        let mut identifiers = vec![self.model.as_str()];
        identifiers.extend(self.aliases.iter().map(String::as_str));
        identifiers
    }
}

#[derive(Clone, Debug, Default, Eq, PartialEq)]
pub(crate) struct WorkerSupervisorGuidance {
    pub(crate) model: String,
    pub(crate) target_patch_lines: Option<u64>,
    pub(crate) max_patch_lines: Option<u64>,
    pub(crate) guidance: Vec<String>,
}

impl WorkerSupervisorGuidance {
    pub(crate) fn is_empty(&self) -> bool {
        self.guidance.is_empty()
            && self.target_patch_lines.is_none()
            && self.max_patch_lines.is_none()
    }

    pub(crate) fn with_patch_line_overrides(
        mut self,
        target_patch_lines: Option<u64>,
        max_patch_lines: Option<u64>,
    ) -> Self {
        if target_patch_lines.is_some() {
            self.target_patch_lines = target_patch_lines;
        }
        if max_patch_lines.is_some() {
            self.max_patch_lines = max_patch_lines;
        }
        self
    }
}

pub(crate) fn default_worker_model_profiles() -> Vec<WorkerModelProfile> {
    vec![
        WorkerModelProfile {
            model: DEFAULT_OPENCODE_MODEL.to_string(),
            aliases: vec![
                DEFAULT_OPENCODE_MODEL.to_string(),
                DEFAULT_OPENCODE_LOCAL_MODEL.to_string(),
                "qwen/qwen3.6-27b".to_string(),
                format!("{DEFAULT_OPENCODE_PROVIDER}/{DEFAULT_OPENCODE_LOCAL_MODEL}"),
            ],
            target_patch_lines: Some(100),
            max_patch_lines: Some(250),
            supervisor_guidance: vec![
                "This worker is cheap and useful for focused source edits, narrow repo inspection, compact command checks, and proposal turns; avoid broad autonomous design work.".to_string(),
                "It can spend a while reasoning before editing; do not assume it is stalled while OpenCode is still producing reasoning, tool, or stdout activity.".to_string(),
                "It can struggle with large effective context before explicit overflow; avoid asking it to reread many files, and use worker_mode=context_focus after context overflow, stale context, or repeated no-delta turns.".to_string(),
                "For broad expected-patch tasks, prefer worker_turn_shape=patch_request: choose the largest coherent source behavior it is likely to complete cleanly, usually one to three focused files, a bounded goal, deferred checks, and optional anchors/snippets or exact_edits when precision saves supervisor output.".to_string(),
                "When route or file choice is unclear, use worker_turn_shape=planning_probe with expect_patch=false: ask it to inspect one to three focused authored-source files or targeted command outputs and propose the next request; do not let it decide task completion.".to_string(),
                "After multiple clean patch_request turns with useful deltas and no context pressure, broaden the next patch_request within the same shape; after messy, broad, or stalled turns, shrink the next slice.".to_string(),
                "Prefer human-authored source edits. Keep generated artifacts, vendored files, lockfiles, snapshots, and build outputs out of the worker-owned patch unless the supervisor explicitly chooses a generated-output step.".to_string(),
                "If generation is useful, ask it to run the generator or focused command as evidence, report the result compactly, and remove generated byproducts unless they are intentionally part of the patch.".to_string(),
                "It may produce directionally useful but messy parser, grammar, generated-code, or broad integration patches; inspect changed-file lists and patch stats before opening large diffs.".to_string(),
                "It may miss end-to-end integration across slices. Before approval, check that helpers, options, parser/generated code, callers, state mutation, and error propagation are wired where the task requires.".to_string(),
                "Do not trust compile success, non-empty diff, or the worker's summary as proof of task completion; require task-derived behavior evidence plus likely negative or edge-case coverage when behavior changed.".to_string(),
                "For option or behavior families with a base path plus modifiers, start with the base behavior and add one modifier family later unless prior worker turns show it can safely combine more.".to_string(),
                "For large functions or code-generation paths, give one literal anchor and the smallest local transformation; include preservation constraints when unrelated branches or formatting churn are likely.".to_string(),
                "When tests cannot start because dependencies are missing, keep the worker focused on repo-level evidence and allowed commands instead of global environment repair.".to_string(),
            ],
        },
        WorkerModelProfile {
            model: "glm-4.7-flash:Q4_K_M".to_string(),
            aliases: vec![
                "glm-4.7-flash:Q4_K_M".to_string(),
                format!("{DEFAULT_OPENCODE_PROVIDER}/glm-4.7-flash:Q4_K_M"),
            ],
            target_patch_lines: Some(180),
            max_patch_lines: Some(400),
            supervisor_guidance: vec![
                "It tends to act readily, but can rewrite or delete too much when asked for broad source changes.".to_string(),
                "For broad expected-patch tasks, prefer worker_turn_shape=patch_request with one source behavior, one focused file, a bounded goal, optional exact_edits when precision is needed, and no tests before editing.".to_string(),
                "For large functions or code-generation paths, include preservation constraints: preserve existing control flow and indentation, do not rewrite the whole function, do not delete or reindent unrelated branches, and edit only the focused block.".to_string(),
                "Prefer worker_mode=continue for revisions so it keeps accumulated file context; use context_focus only when the previous worker context is clearly harmful.".to_string(),
                "Before accepting a turn, check whether the diff is too broad or destructive for the requested patch.".to_string(),
            ],
        },
        WorkerModelProfile {
            model: "openrouter/z-ai/glm-5.2".to_string(),
            aliases: vec![
                "openrouter/z-ai/glm-5.2".to_string(),
                "z-ai/glm-5.2".to_string(),
            ],
            target_patch_lines: Some(300),
            max_patch_lines: Some(800),
            supervisor_guidance: vec![
                "This worker is capable, but may over-investigate when the handoff contains an apparent implementation constraint conflict or an unresolved toolchain choice.".to_string(),
                "For generated-code, parser/compiler, toolchain, or similar trap-prone tasks, resolve the implementation route in the supervisor handoff before invoking the worker; do not ask the worker to discover whether the obvious route is viable.".to_string(),
                "When the supervisor has selected a route, tell the worker to trust that route unless a direct compile, test, or command result proves it impossible.".to_string(),
                "For broad expected-patch tasks, prefer worker_turn_shape=bounded_feature_slice with one concrete implementation path, one to three focused files, and the first reversible source edit named explicitly.".to_string(),
                "Make the initial handoff patch-first: include the chosen strategy, the exact next behavior slice, the files to touch, and deferred checks; avoid leaving design forks for the worker to resolve before editing.".to_string(),
                "If the worker starts toolchain archaeology, scratch-file probing, broad repo reading, or test-before-edit behavior without a diff, use live control to restate the chosen implementation route and request an immediate focused source edit.".to_string(),
                "For revisions, anchor the next instruction to the current accumulated patch, preserve useful existing edits, and name the next missing behavior instead of restarting discovery.".to_string(),
                "Before approval, check that the accumulated patch implements the requested end-to-end behavior, not just the first structural field or helper, and require focused behavior evidence for the main path plus likely invalid or edge case.".to_string(),
            ],
        },
    ]
}

fn normalize_model_identifier(value: &str) -> String {
    value.trim().to_ascii_lowercase()
}
